# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4727bfa4342c1e128c63056c94e1217ce7c60082761e476e2f9bfe2e792ec3e4153b7eb6736062cdda9701f76c7b5b2185d11ae9005667ecd9e4fbd330a0c88a

test:
  secret_key_base: f2f5fa08dfa50d4d8668d490bd1282174ffe23b81557e4be93e65ec004ff6671726051980dc51382a68ce27b858c94b03c3290844c63d9f5060eacbaa1cfe619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
